#!/usr/bin/env bash

filter="-mmin -120"
if [[ "$1" == "all" ]]; then
    filter=""
fi

# shellcheck disable=SC2086
find ./*.jpg ./*.png $filter -printf '%f\0' | while IFS= read -r -d '' img; do
    echo "Updating thumbnail for $img"
    magick "$img" -resize 10% "thumbs/$img"
done
