#!/usr/bin/env bash

filter="-mmin -120"
if [[ "$1" == "all" ]]; then
    filter=""
fi

# shellcheck disable=SC2086
find ./dark/*.jpg ./dark/*.png $filter -printf '%f\0' | while IFS= read -r -d '' img; do
    echo "Updating thumbnail for \"$img\" (dark)"
    magick "dark/$img" -resize 10% "dark/thumbs/$img"
done

# shellcheck disable=SC2086
find ./light/*.jpg ./light/*.png $filter -printf '%f\0' | while IFS= read -r -d '' img; do
    echo "Updating thumbnail for \"$img\" (light)"
    magick "light/$img" -resize 10% "light/thumbs/$img"
done
